INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("MR. CHOCOLATE", 12, "M", "BROWN", "MEAN", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("ROWDY", 13, "M", "BLACK", "HAPPY", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("TABITHA", 8, "F", "BROWN", "ANGRY", 'FALSE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("SERGEANT BROWN", 4, "M", "BROWN", "PLAYFUL", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("MELISSA", 6, "F", "BLACK", "MEAN", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("GRINCH", 9, "M", "BROWN", "MEAN", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES ("WENDY", 11, "F", "BROWN", "MEAN", 'TRUE');
INSERT INTO BEARS (NAME, AGE, GENDER, COLOR, TEMPERAMENT, ALIVE) VALUES (NULL, 12, "M", "BROWN", "MEAN", 'FALSE');
